"""create users and books tables

Revision ID: 3f5a2ef72fd5
Revises: 42362d4ce6f5
Create Date: 2025-12-07 21:15:15.695242

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '3f5a2ef72fd5'
down_revision: Union[str, Sequence[str], None] = '42362d4ce6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
