"""create users and books tables

Revision ID: 42362d4ce6f5
Revises: 7e051879e6eb
Create Date: 2025-12-07 21:10:41.645391

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '42362d4ce6f5'
down_revision: Union[str, Sequence[str], None] = '7e051879e6eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
